Repository Humanizr/Humanizer, pull requests merged in 2024-02, with the labels that each got.

#1082 Fix Japanese single year translation
  src/Humanizer.Tests.Shared/Localisation/ja/TimeSpanHumanizeTests.cs
  src/Humanizer/Properties/Resources.ja.resx
Labels: localisation

#1426 Fix missing resources errors
  src/Humanizer/Localisation/Formatters/DefaultFormatter.cs
  src/Humanizer/Properties/Resources.resx
Labels: bug

#1434 Remove EnumDescriptionPropertyLocator and add replacement UseEnumDescriptionPropertyLocator
  src/Humanizer.Tests.Shared/EnumHumanizeTests.cs
  src/Humanizer.Tests/ApiApprover/PublicApiApprovalTest.Approve_Public_Api.DotNet8_0.verified.txt
  src/Humanizer.Tests/ApiApprover/PublicApiApprovalTest.Approve_Public_Api.Net4_8.verified.txt
  src/Humanizer/Configuration/Configurator.cs
Labels: breaking api

#1442 ToTitleCase Perf improvements
  src/Benchmarks/TransformersBenchmarks.cs
  src/Humanizer/Transformer/ToTitleCase.cs
Labels: perf

#1457 spanify RomanNumeralExtensions
  src/Humanizer.Tests/ApiApprover/PublicApiApprovalTest.Approve_Public_Api.DotNet8_0.verified.txt
  src/Humanizer.Tests/ApiApprover/PublicApiApprovalTest.Approve_Public_Api.Net4_8.verified.txt
  src/Humanizer/RomanNumeralExtensions.cs
Labels: perf

#1458 Enabling Trimming
  src/Humanizer.Tests/ApiApprover/PublicApiApprovalTest.Approve_Public_Api.DotNet8_0.verified.txt
  src/Humanizer/EnumCache.cs
  src/Humanizer/EnumDehumanizeExtensions.cs
  src/Humanizer/EnumHumanizeExtensions.cs
  src/Humanizer/Humanizer.csproj
Labels: perf

#1460 Fix Bulgarian TimeSpan to words & genders in number to words
  src/Humanizer.Tests/Localisation/bg/NumberToWordsTests.cs
  src/Humanizer.Tests/Localisation/bg/TimeSpanHumanizeTests.cs
  src/Humanizer/Configuration/FormatterRegistry.cs
  src/Humanizer/Localisation/Formatters/BulgarianFormatter.cs
  src/Humanizer/Localisation/NumberToWords/BulgarianNumberToWordsConverter.cs
  src/Humanizer/Properties/Resources.bg.resx
Labels: bug

#1463 Optimize English to words converter
  src/Benchmarks/EnglishToWordsBenchmark.cs
  src/Humanizer.Tests/NumberToWordsTests.cs
  src/Humanizer/Localisation/NumberToWords/EnglishNumberToWordsConverter.cs
Labels: perf
